### ISSUE TITLE
Can‘t open the link of MATLAB scripts in http://gotm.net

### ISSUE THREAD

**Issue by zhouaming9** [gotm-model/gotm-model-hugo#1]
When I want to download some MATLAB scripts of idealized cases (eg: MATLAB scripts in http://gotm.net/cases/channel/), the site went error. Would you please fix it and send me the MATLAB scripts of idealized cases?

**Comment by bolding** [comment]
the channel and couette cases has been updated with python scripts linked directly to the GitHub repository
